### ISSUE TITLE
Qt Packages

### ISSUE THREAD

**Issue by khaneliman** [snowfallorg/lib#11]
Does this not support qt packages in the current form? I am trying to make a derivation that has inputs of qtbase, qttools, etc per https://nixos.wiki/wiki/Qt#Packaging but am getting errors 

> error: evaluation aborted with the following error message: 'Function called without required argument "qtbase" at /nix/store/gnv998h2yy5bwinhd2001jwx3w8mwxq6-52zvnzam637mckyk4iiafm09h4dhg0bq-source/packages/btrfs-assistant/default.nix:6, did you mean "hbase", "qtpass" or "xbase"?'

According to the wiki that means it needs to be called with a different method than a normal package

> #nix-repl
myapp = callPackage ./build/myapp/default.nix { } # Will complain it wasn't called with qtbase, etc.
myapp = libsForQt5.callPackage ./build/myapp/default.nix { } # Should work

Does this code need to be updated in snowfall lib to support this special case of needing a different caller? Is there a workaround I can do for this ?

```nix 
https://github.com/snowfallorg/lib/blob/main/lib/package/default.nix
create-package-metadata = package: {
          name = builtins.unsafeDiscardStringContext (snowfall-lib.path.get-parent-directory package);
          drv = pkgs.callPackage package {
            inherit channels;
            lib = snowfall-lib.internal.system-lib;
          };
        };
```

I think the README coincides with what I saw from that line... 
> │ An optional set of packages to export.
├─ packages/
│  │
│  │ Any (nestable) directory name. The name of the directory will be the
│  │ name of the package.
│  └─ **/
│     │
│     │ A Nix package to be instantiated with `callPackage`. This file
│     │ should contain a function that takes an attribute set of packages
│     │ and *required* `lib` and returns a derivation.
│     └─ default.nix

**Comment by jakehamilton** [comment]
Thanks for creating this issue!

I don't think there's a great solution here due to the current state of qt support in NixPkgs. I can think of two possible solutions, but they both have problems:

- Use `libsForQt5.callPackage` yourself within your package's `default.nix` file.

This should work to allow you to build things, but overriding the created package may be weird or not work. Haven't tried this, though, so perhaps it's viable?

- Using `outputs-builder` to create the package on your flake output manually.

This avoids any Snowfall Lib layering, but comes at the cost of not having access to much of the niceties the automatic solution provides. You'll miss out on automatic overlay generation for example.

**Comment by jakehamilton** [comment]
Going to close this issue for now since this is more of an upstream problem. Right now the solution would be to use the qt-specific callPackage within your `default.nix`.

**Comment by poperigby** [comment]
> Use libsForQt5.callPackage yourself within your package's default.nix file.

@jakehamilton I'm having some trouble figuring out how to do this. Can you give an example, please?

**Comment by poperigby** [comment]
Never mind, I figured it out. I just to move my package to a separate `package.nix` file, and then put this in my package's `default.nix`:

```nix
{ qt6Packages, ...}:

qt6Packages.callPackage ./package.nix {}
```
