### ISSUE TITLE
Status of  snowfallorg/lib

### ISSUE THREAD

**Issue by osv** [snowfallorg/lib#16]
Hi, would like to know direction of this project. When dev branch can be merged to master and used by other users as stable.
Maybe there is list of features that you want to finish before merging?

**Comment by jakehamilton** [comment]
Hey @osv 👋

We're getting pretty close to being able to release the next version of Snowfall Lib. Right now all of the features I wanted to include in V2 are in. The only thing lacking is documentation. I don't want to push out the new version and have people confused as to why certain things are broken (due to changes) and I'd like to make it easier for newcomers to get started with Snowfall Lib V2 as well. To that end I'm working on getting a better documentation site going for Snowfall Lib. Once that is up we'll be ready to push out the new version!

**Comment by osv** [comment]
Thanks! ! will close this.
