### ISSUE TITLE
Acessing lib in overlays

### ISSUE THREAD

**Issue by noonien** [snowfallorg/lib#37]
How can libs be accessed in an overlay?

I've tried the following without success:
```
{my-input, ...}: final: prev: # my-input.lib
{<namespace>, ...}: final: prev: # <namespace>.lib
_: final: prev: # prev.lib.my-lib, prev.<namespace>.lib.my-lib, prev.lib.<namespace>.my-lib
_: final: prev: # final.lib.my-lib, final.<namespace>.lib.my-lib, final.lib.<namespace>.my-lib
```

**Comment by jakehamilton** [comment]
Ah, the modified lib is not injected in overlays. You should be able to access it via the `self` input.

**Comment by jakehamilton** [comment]
Coming back to this, I forgot to mention that we don't want to be patching the lib in an overlay since that overlay would be consumed by other flakes and have their own `lib` overridden. I think the short-term answer here is going to be using `inputs.self.lib` and the long-term answer will be having Snowfall Lib pass `lib` as one of the arguments to the overlay factory.

**Comment by jakehamilton** [comment]
I've added `lib` as an argument in the latest commit on the `dev` branch!

**Comment by jakehamilton** [comment]
Closing this now that v3 is released.
