### ISSUE TITLE
Multi-user Home Manager

### ISSUE THREAD

**Issue by craiggwilson** [snowfallorg/lib#44]
First off, I love how easy this made setting up a nix environment, so thank you!

I'm attempting to support multiple users on a single machine and assumed I could just create two homes. This works, except I can't enable different home-manager modules for each. For example, any modules I put into `modules/home/<xxxxx>` seem to be shared across all users for a given host. As such, enabling `bat` via a custom module means it can't be enabled for another user, and yet still isn't enabled for both due to ordering I assume.

I've been looking through the source code and it _feels_ like all these modules are plugged in to home-manager's shared modules when it seems like they should be created new for each user. Shared things should go into the `modules/nixos/<xxx>` path.

I feel like I've misunderstood something so if this is how it's supposed to be, I'll need to figure out how else to create custom modules that are different between home-manager users.

**Comment by jakehamilton** [comment]
Hey there! Glad Snowfall Lib has been helpful!

I think what you're looking for is creating your own modules that expose `options` and `config`. You're correct that all modules in `modules/` are loaded for the system or Home-Manager (`nixos`, `darwin`, `home`). This is by design and is also how the NixOS modules provided by NixPkgs, Darwin modules provided by nix-darwin, and Home Modules provided by Home-Manager function. These modules all specify an `enable` option which then dynamically applies the configuration for that module.

I do the same in my configuration here in case this helps:

https://github.com/jakehamilton/config/blob/f8f8d3d70a7ef58f9d030fe36d35caa7054fdcec/modules/home/tools/direnv/default.nix

With the above example I can then set `plusultra.tools.direnv.enable = true;` in my user home configuration and that will apply the `config` from the linked module. This also lets you do dynamic customization per-user and per-system! For example, here I have a Git module:

https://github.com/jakehamilton/config/blob/f8f8d3d70a7ef58f9d030fe36d35caa7054fdcec/modules/nixos/tools/git/default.nix

This module comes with multiple options that can be configured, but start with default values that often work out of the box (for me). This way I can still modify certain values if necessary while reusing configuration from modules.

**Comment by jakehamilton** [comment]
This should now be fixed fully on `dev` :+1:

**Comment by YaroKasear** [comment]
I was about to ask about this, actually. I was going about setting up a dedicated work user and I tried enabling one module for one user while disabling it for another user and got an error about conflicting definition values when I was expecting it to just output a configuration for each user, one with the module and one without the module enabled.

Is this the same problem as described here?

**Comment by jakehamilton** [comment]
@YaroKasear can you link a branch where this is happening? It would help to see what modules and users aren't working for you.

**Comment by jakehamilton** [comment]
@YaroKasear can you try switching to the dev branch of Snowfall Lib?

**Comment by YaroKasear** [comment]
> @YaroKasear can you try switching to the dev branch of Snowfall Lib?

The dev branch fixes the issue (I pushed the changes I tested to the branch.). Would it be wise for me to stick with the dev branch from now on?

**Comment by jakehamilton** [comment]
@YaroKasear yes, at least until v3 is released :)

**Comment by craiggwilson** [comment]
Arg... for some reason I didn't receive any alerts about this. My apologies and thanks so much for responding. I'll move to v3 shortly and see if that addresses my problem. My guess is that it will.
