### ISSUE TITLE
How to make snowfall-lib-ified modules work in declarative containers?

### ISSUE THREAD

**Issue by JeanMertz** [snowfallorg/lib#49]
Given this config:

```nix
{ lib, inputs, ... }:
let
  root = inputs.self;
in {
  containers.foo = {
    config = { ... }: {
      imports = [ (root + /modules/nixos/services/foo.nix) ];
      system.stateVersion = "23.11";
    };
  };
};
```

Inside the `config` block you basically have an entire fresh NixOS configuration available to you. However, because `modules/nixos/services/foo.nix` was written with the expectation of (and need for) snowfall-lib injected types, this fails to build, as those types aren't actually accessibly inside the container configuration.

Specifically, `foo.nix` starts with:

```nix
{ lib, ... }:
with lib;
with lib.my_namespace;
```

But this fails because the `my_namespace` attribute isn't available, whereas it normally is if I import this module from outside the container context.

How can I get these modules to work similarly inside containers as they do outside?

**Comment by jakehamilton** [comment]
Ah I think this would require some changes on the Snowfall Lib side of things. Right now we're wrapping modules manually to allow for imported variants (as opposed to using specialArgs since that would apply to _every_ module). As things stand right now I don't think modules reliant on Snowfall Lib attributes will work as NixOS containers since that performs its own eval that we can't control: https://github.com/NixOS/nixpkgs/blob/9f2ee8c91ac42da3ae6c6a1d21555f283458247e/nixos/modules/virtualisation/nixos-containers.nix#L485

**Comment by JeanMertz** [comment]
Thank you for that explainer. That’s unfortunate to hear. I reallly like the structure this project brings, but I also use a lot of containers. 

Any hacky workarounds you can think of, that’ll allow me to keep using this lib until containers are properly supported?

**Comment by JeanMertz** [comment]
That makes sense. I guess what I could try and do until then, is have my own container module that wraps all the boilerplate to provide access to all of Snowfall Lib's modules, and use that for now, until an abstraction is in place that can go into the lib itself.

**Comment by jakehamilton** [comment]
Thinking about this some more I think it would make sense if this were supported via Snowfall Lib itself. I think we may be able to handle things if we impose a `systems/containers/` directory. With that we should be able to populate modules and specialArgs. However, there may be quirks similar to the implementation for Home-Manager where I needed to manage alias definitions myself in order to allow for configuration to pass through from the system to the inner module evaluation.

**Comment by daagaak** [comment]
I'm also curious about this, as I suspect that [microvm](https://github.com/astro/microvm.nix)'s will suffer from the same problem?

**Comment by daagaak** [comment]
This seems to work and produces a correct looking(?!) derivation that ends up being the system root of the inner container:
```
  containers."lead-new" = {
    autoStart = true;
    hostBridge = "br11";
    privateNetwork = true;
    path = inputs.self.nixosConfigurations."lead-new".config.system.build.toplevel;
  };
```

**Comment by jakehamilton** [comment]
I don't have plans to work on this for the foreseeable future, but if there is enough interest in Snowfall Lib providing support for nixos-containers then it can be reconsidered.

**Comment by YaroKasear** [comment]
> This seems to work and produces a correct looking(?!) derivation that ends up being the system root of the inner container:
> 
> ```
>   containers."lead-new" = {
>     autoStart = true;
>     hostBridge = "br11";
>     privateNetwork = true;
>     path = inputs.self.nixosConfigurations."lead-new".config.system.build.toplevel;
>   };
> ```

I'd be curious about seeing your configuration for that container, since when I try that workaround it asks me for a lot of things like filesystems and a boot device. Most the containers I configured work fine, but now I'm trying to work with one that'd use a package and module I wrote for something not in nixpkgs and it's definitely not been going

I'd definitely be interested in a possible containers feature for snowfall-lib.

**Comment by justinmartin** [comment]
I would use this if/when it is added.

**Comment by daagaak** [comment]
> since when I try that workaround it asks me for a lot of things like filesystems and a boot device

This can be fixed by setting the inner container to be a container, which disables a bunch of checks/services that don't apply when you're inside an LXC container:
```
boot.isContainer = true
```
