### ISSUE TITLE
Nested package structure?

### ISSUE THREAD

**Issue by olistrik** [snowfallorg/lib#52]
Hi there,

I've noticed that unlike modules, nesting package directories does not extend the namespace of the generated package set.

For example:

```
.
└─── packages
    └── vimPlugins
        └── foo-bar
            └── default.nix
```

does not result in `pkgs.olistrik.vimPlugins.foo-bar` but in `pkgs.olistrik.foo-bar`.

Is it possible to produce this nested structure in snowfall lib?

**Comment by jakehamilton** [comment]
Hey there! Nested packages aren't currently something that are supported, partially because of the difference that would imply on the package set compared to the flake outputs. I think modules tend to benefit much more than packages would here.

If you do really want to nest packages, you can add them via an overlay.

---

I think this is more of a Nix Flakes problem. Because of the flat structure of `outputs.packages`, we can't really create any useful collections like `vimPlugins`. This seems to have been mostly ignored due to NixPkgs not having to adhere to this structure since it still uses `outputs.legacyPackages`.

**Comment by olistrik** [comment]
Thanks for the quick response!

Until now I've always exported my packages as overlays, so I've never noticed that `outputs.packages` didn't support nesting!

I mainly follow the nesting of collections because that's what `NixPkgs` does, but as that isn't how flakes do it I'll just change the way I think about packages.
