### ISSUE TITLE
Support multiple `snowfall`-style source directories

### ISSUE THREAD

**Issue by RuRo** [snowfallorg/lib#6]
Hi. First of all, I wanted to thank you for building this library. I implemented a very similar system myself, except mine was extremely jank, so when I saw your version, I immediately switched to it and I have no regrets so far :grin:. I think, that you should try to advertise your library more (on [discourse.nixos.org](https://discourse.nixos.org/), for example).

The only feature that I am missing from my jank version, is the ability to extend/merge multiple `snowfall`-style flakes. In my experience, this is really useful when working with private configs or when you want to quickly test some stuff on one particular system without committing to the "shared" config.

I guess, the "simplest" way to support that would be to make it so that `src` (or `snowfall.root` in version 2 if I understand #5 correctly) would also accept a list of `Path`s and then scan them all. What do you think?

**Comment by RuRo** [comment]
Ah, actually, I missed one more thing. I used to have 2 separate directories - `nixosModules` and `hmModules`. With the former getting added to the `modules` argument of `lib.nixosSystem` and the latter - to `config.home-manager.sharedModules`.

Do you think, a similar system could be included in `snowfall`?

**Comment by RuRo** [comment]
P.S. If you are interested in adding these features to `snowfall`, but don't have the motivation/time to implement them, I am willing to try making a PR for both of them.

**Comment by jakehamilton** [comment]
Hey @RuRo!

> the ability to extend/merge multiple snowfall-style flakes

I'm not too sure how exactly a feature like this would work (or if it should). Would you be able to provide an example for how you imagine this being set up? Part of the trouble with making `snowfall.root` a list is that the value is used in quite a few places, expecting a single path. So that would mean changing nearly every file in the library to support multiple paths. It would also complicate things from the user's perspective if they wanted to reference a file from their snowflake root since they'd have to filter multiple results.

I wonder if there's a good way to handle this outside of Snowfall Lib such that you can provide a merged directory to `snowfall.root` instead? That'd be difficult since using `symlinkJoin` (or similar) requires a package set and therefore system. Might be worth playing around to see if there's a good way to do that.

> have 2 separate directories - nixosModules and homeModules

I have been thinking about this! I [posted about it](https://hachyderm.io/@jakehamilton/109913131938588839) the other day and some of the things I'm considering before adding this:

- There are at least 3 targets currently: NixOS, Darwin, and home-manager.
- Some modules can pretty easily support both NixOS and Darwin at the same time.
- home-manager often requires unique configuration and there are additional quirks to be aware of.
- In _some_ cases it may be possible to support NixOS, Darwin, and home-manager with the same module. Is that worth supporting? At that point do you expect duplicates to avoid the many foot-guns?

I'd like to change the module support to use system-specific directories like: `modules/nixos/`, `modules/darwin/`, `modules/home/`. That would load modules for NixOS and Darwin as well as loading home-manager modules (likely how you mentioned with `sharedModules`, though I'm not too familiar with that at the moment).

I think for this change I'll want to hold out for a bit longer so I make sure that I get it right.

**Comment by RuRo** [comment]
Hi. Sorry for the late reply, I must have missed the notification.

> > the ability to extend/merge multiple snowfall-style flakes
> 
> I'm not too sure how exactly a feature like this would work (or if it should). Would you be able to provide an example for how you imagine this being set up?

From the user perspective, I think just accepting multiple roots should be sufficient. Basically, I used to split my flake into 3 parts "common", "private" and "override". Where common and private are versioned with git (but private is not readable to the public) and "override" is just whatever lives in `/etc/nixos/` (override is not versioned, so that I can try out stuff quickly).

I think that my exact use case is not too important. The main point is that all 3 flakes would ideally utilize the directory layout. But just doing a `mkFlake` in all 3 of them is not sufficient, because you then have to manually merge/import them to make every package/lib/module etc available in the final flake. With multiple roots I would just do something like

```nix
# sourceC/flake.nix
inputs.snowfall-lib.mkFlake {
    inherit inputs;
    roots = [ inputs.sourceA.outPath inputs.sourceB.outPath ./. ];
};
```

> So that would mean changing nearly every file in the library to support multiple paths. It would also complicate things from the user's perspective if they wanted to reference a file from their snowflake root since they'd have to filter multiple results.

Hm. Yeah, I haven't thought about that. Maybe, another way this could be resolved is with something like
```nix
# sourceC/flake.nix
inputs.snowfall-lib.mkFlake {
    inherit inputs;
    snowfall-imports = [ inputs.sourceA inputs.sourceB ];
    root = ./.;
};
```

Where `snowfall-imports` takes a list of flakes that are themselves produced by `snowfall-lib.mkFlake` and makes all the lib/packages/modules/systems/etc directly available to the current flake "as if" they were defined locally in `sourceC` root.

> > have 2 separate directories - nixosModules and homeModules
> 
> I have been thinking about this! I [posted about it](https://hachyderm.io/@jakehamilton/109913131938588839) the other day and some of the things I'm considering before adding this:
> 
> * There are at least 3 targets currently: NixOS, Darwin, and home-manager.
> * Some modules can pretty easily support both NixOS and Darwin at the same time.
> * home-manager often requires unique configuration and there are additional quirks to be aware of.
> * In _some_ cases it may be possible to support NixOS, Darwin, and home-manager with the same module. Is that worth supporting? At that point do you expect duplicates to avoid the many foot-guns?

I am not too familiar with Darwin, but in my experience NixOS and home-manager aren't that similar, so sharing modules between them isn't all that useful imho (especially given that we can already share `lib`s). Also, I think, that you can get shared modules "for free" by just adding a symlink from `nixos/common` and `darwin/common` to `common` and then putting all the common modules there.

> I'd like to change the module support to use system-specific directories like: `modules/nixos/`, `modules/darwin/`, `modules/home/`.

I would actually prefer all the module directories to stay at the top level (so `nixos`, `darwin` and `home` instead of `modules/nixos`, `modules/darwin`, `nixos/home`). But this is just my preference, so I don't have strong reasons for it.

**Comment by jakehamilton** [comment]
This does seem interesting, but I think there are a good amount of technical issues implementing this (in addition to being able to handle these use cases in a different way currently). As such I'm going to close this issue.
