### ISSUE TITLE
Support for unix module (darwin or nixos) 

### ISSUE THREAD

**Issue by awlsring** [snowfallorg/lib#91]
Had question on how modules are implemented. Reading through the documentation, it seems there are 3 types of supported modules, nixos, darwin, and home. Currently on my non-snowfall flake, I have a few modules that can be utilized by either a nixos or darwin system as they operate on some attributes that are uniform across both releases. This is things like stylix, tailscale, programs, etc.

Is this something that could be supported here? Work around could probably be just define it twice, but I was curious if anything in snowfall would allow for having some shared "unix" module (nixos or darwin).

**Comment by jakehamilton** [comment]
Due to the differences between the platforms I don't think this is something that Snowfall Lib will add, but you can put these modules in another directory and use `create-modules` to produce a set of modules you can share between things.

https://snowfall.org/reference/lib/#libsnowfallmodulecreate-modules
