### ISSUE TITLE
Structure suggestion

### ISSUE THREAD

**Issue by tholoo** [snowfallorg/lib#95]
hi, thanks for making this awesome library.
I recently moved my config from traditional nix to snowfall, and the only thing I miss is having all config related to a system in one folder. Currently, if I have a system called "apple", I have to define:

- The system configuration in `systems/x86_64-linux/apple`
- User configurations in `homes/x86_64-linux/user1@apple`, `homes/x86_64-linux/user2@apple`, etc., alongside users for other systems
- Any overrides, extra modules, deployment settings, and other details in `flake.nix`

So, for one system, I have to hop between these locations.
what do you think about having one folder, for example called hosts, that contains everything related to one system? like this: 

- System configurations would be in `hosts/x86_64-linux/apple/config.nix`
- Details about apple that is currently defined in `flake.nix` would be in `hosts/x86_64-linux/apple/default.nix`
- User definitions would be in `hosts/x86_64-linux/apple/homes/user1/default.nix` and `hosts/x86_64-linux/apple/homes/user2/default.nix
`- 
(note that in this case we won't need to define the hostname after @, as it would be redundant).
```
hosts/
└── x86_64-linux/
    └── apple/
        ├── config.nix
        ├── default.nix
        └── homes/
            ├── user1
            └── user2
```
maybe `x86_64-linux` could also be defined in `default.nix` to reduce nesting? I'm not sure if that's possible.
thanks again.

**Comment by jakehamilton** [comment]
I'm not sure that I will end up supporting this due to it being less flexible than the current structure. Things like homes without a specific host would still need a place to go. If you still prefer to colocate these things then you can create these files and import them manually in your config. Though you will miss out on some of the niceties of Snowfall Lib if you do not define a home entry.

I'll give this some more thought, but at least for now I don't think this is going to be implemented.
